# When there is no rules specified here, sass-lint takes the default configuration, which can be found in the below link.
# Default configuration -> https://github.com/sasstools/sass-lint/blob/master/lib/config/sass-lint.yml

# To override, uncomment the below lines and add the rules

rules:
  no-important: 0
  no-color-literals: 0
  class-name-format: 0
  no-invalid-hex: 0
  no-qualifying-elements: 0
  nesting-depth: 0
  no-ids: 0
  no-transition-all: 0
  no-vendor-prefixes: 0
  no-misspelled-properties: 0
  leading-zero: 0
